In [23]:
import numpy as np
from ContNoRegret.Domains import unitbox
from ContNoRegret.LossFunctions import PolynomialLossFunction, random_PolynomialLosses
from scipy.stats import norm, uniform
dom = unitbox(2)
tmpfolder = '/Volumes/tmp/'
M = 10
L = 5
T = 500
nus = [1.05, 2]

In [24]:
while len(lossfuncs) < T:
    tmpfuncs = np.array(random_PolynomialLosses(dom, 10, M, L, 4, [0,1,2,3,4], dist=uniform(loc=0, scale=3)))
    normbounds = {nu: np.array([lossfunc.norm(2/nu, tmpfolder=tmpfolder) for lossfunc in tmpfuncs]) for nu in nus}
    Ms = {nu: np.array(normbounds[nu]) for nu in nus}
    for i in range(len(normbounds)):
        ratio = normbounds[nus[0]][i]/normbounds[nus[1]][i]
        if ratio > 1.75:
            lossfuncs.append(tmpfuncs[i])
            print(len(lossfuncs))
        

201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305

/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/__main__.py:6: RuntimeWarning: invalid value encountered in double_scalars
/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/__main__.py:6: RuntimeWarning: invalid value encountered in double_scalars



306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440

/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/__main__.py:6: RuntimeWarning: invalid value encountered in double_scalars
/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/__main__.py:6: RuntimeWarning: invalid value encountered in double_scalars



441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500


/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/kernel/__main__.py:6: RuntimeWarning: invalid value encountered in double_scalars


In [26]:
coeffs = [list(lf.coeffs) for lf in lossfuncs]
expos = [lf.exponents for lf in lossfuncs]
with open('coeff_expos_n2.py', 'w') as f:
    f.write('coeffs = ' + str(coeffs) + '\n' + 'exponents = ' + str(expos))

In [9]:
[(lossfunc.norm(1.05, tmpfolder=tmpfolder), lossfunc.norm(2, tmpfolder=tmpfolder)) for lossfunc in lossfuncs]

[(0.031938465259162663, 0.067454455675304489),
 (0.014433357847643279, 0.031542985813273069),
 (0.013894345062018915, 0.029345759551757347),
 (0.024812292248224059, 0.052231451529516068),
 (0.010930993861242791, 0.028069393813845496),
 (0.011124609412963508, 0.028566573781076392),
 (0.0230449009782949, 0.047141297838764577),
 (0.017554728909267608, 0.035239457749515736),
 (0.017498013294863606, 0.036834932876678883),
 (0.033314563170601309, 0.07057553257702838)]

In [19]:
from coeff_expos_n2 import coeffs,exponents

In [12]:
[lossfunc.coeffs for lossfunc in lossfuncs]

[array([ -7.15378450e-07,  -2.15176337e+00,  -2.56553649e-01]),
 array([ -1.38884691e+02,   2.29742538e-12]),
 array([ -4.70784903e+02,   1.99297112e-16]),
 array([ -1.97731168e-12,   2.01804453e+02,   1.20161595e+02])]

In [21]:
cfs[0]

[52.942672264359736, -8.743625497449273e-13, 51.122271544881364]

In [22]:
xpnts[0]

[(4, 2), (0, 0), (4, 3)]

In [25]:
lossfuncs

In [27]:
from coeff_expos_n2 import coeffs,exponents

In [29]:
lossfuncs = [PolynomialLossFunction(dom, coeff,expo) for coeff,expo in zip(coeffs,exponents)]

In [32]:
lossfuncs[0].exponents

[(4, 2), (0, 0), (4, 3)]